INSERT INTO MODELCLASS(ID, CODE, TITRE, DUREE) VALUES('1', 'code1', 'titre1', 3);
INSERT INTO MODELCLASS(ID, CODE, TITRE, DUREE) VALUES('11', 'code11', 'titre11', 3);
INSERT INTO MODELCLASS(ID, CODE, TITRE, DUREE) VALUES('21', 'code21', 'titre21', 2);
INSERT INTO MODELCLASS(ID, CODE, TITRE, DUREE) VALUES('31', 'code31', 'titre31', 2);
INSERT INTO LINKED_MODELCLASS(parentID, childID) VALUES('11', '21');
INSERT INTO LINKED_MODELCLASS(parentID, childID) VALUES('11', '31');
